version: '3.1'

services:

  web:
    build: .
    restart: always
    ports:
      - 8080:80
    volumes:
      - pretix-data:/data
    links:
      - db
      - redis
    environment:
      PRETIX_URL: http://localhost:8080
      PRETIX_DB_NAME: pretix
      PRETIX_DB_USER: pretix
      PRETIX_DB_PASSWORD: pretix
      PRETIX_DB_HOST: db
      PRETIX_MAIL_FROM: test123@pleio.nl
      PRETIX_MAIL_HOST: 172.17.0.1
      PRETIX_REDIS_LOCATION: redis://redis:6379/0
      PRETIX_CELERY_BACKEND: redis://redis:6379/1
      PRETIX_CELERY_BROCKER: redis://redis:6379/2

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pretix
      POSTGRES_USER: pretix

  redis:
    image: redis
    restart: always

volumes:
  pretix-data:
